### ISSUE TITLE
How should I run python example on a local node?

### ISSUE THREAD

**Issue by pkuphy** [dfuse-io/dfuse-eosio#103]
Hi,

I tried to subscribe live transactions using python (example [here](https://github.com/dfuse-io/docs/blob/master/quickstarts/python/main.py)).

How to set up the auth endpoint and the api key?

**Comment by maoueh** [comment]
On a local node, authentication is disabled, so you can simply skip those steps. You don't need any authentication to talk to the services located in your local node.

I'll let the ticket open for now because I have concerns that the gRPC connection to our service will require you to use a different port and maybe a different setting completely.

Tell us how it goes.

**Comment by pkuphy** [comment]
I've figured out how to do it, here is my example: https://github.com/pkuphy/dfuse-graphql-over-grpc

**Comment by maoueh** [comment]
Really cool :) Glad you resolved it, very easy streamlined example by the way.
