### ISSUE TITLE
How to create two mindreader instance

### ISSUE THREAD

**Issue by zh041x** [dfuse-io/dfuse-eosio#110]
How to create two mindreader instance,I try to execute dfuseeos start mindreader twice but the latter failed cause by port conflict(1065 and 13010).In addtion, there are errors "tracking fetch errors in order: tracker block not found". Do I get the example yaml file for two mindreader instance executing?

**Comment by sduchesneau** [comment]
The 'tracking fetch error' is non-critical (it's repeated less in following commits)

* to start two mindreaders on the same IP address, you need to run them from different paths, and override the following flags:
```      --mindreader-grpc-listen-addr string                     Address to listen for incoming gRPC requests (default ":13010")
      --mindreader-manager-api-addr string                     The dfuse Node Manager API address (default ":13009")
      --mindreader-nodeos-api-addr string                      Target API address to communicate with underlying nodeos (default ":9888")
```

* You will also need to modify the config.ini in the `./mindreader/` folder so that nodeos itself listens to a different port than 9888; (`http-server-address`), that port should be the same that you set for mindreader-nodeos-api-addr. `p2p-listen-endpoint` should also be different to prevent issues.


* for metrics subsystem to work (prometheus export), you can also set those to a different port than 9102:
 ```    --dashboard-metrics-api-addr string                      HTTP address where to reach the metrics API endpoint (default "http://127.0.0.1:9102")
      --metrics-listen-addr string              If non-empty, the process will listen on this address to server Prometheus metrics (default ":9102")
```

* and the 1065 is a special port that allows changing log level at runtime, it is non-essential, but can ben overriden like this:
```      --log-level-switcher-listen-addr string   If non-empty, the process will listen on this address for json-formatted requests to change different logger levels (see DEBUG.md for more info) (default "localhost:1065")
```

I'm giving you the flags to override, but you can set them in your dfuse.yaml files too.
