### ISSUE TITLE
accounthist: off-by-one

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#136]
Running: 

dfuseeos start -c '' accounthist --common-blocks-store-url=gs://dfuseio-global-blocks-us/eos-mainnet/v3  --accounthist-flush-blocks-interval **10** --accounthist-max-entries-per-account 5 --accounthist-start-block-num 5000000 --accounthist-shard-num 0 --accounthist-stop-block-num **5000100** --common-blockmeta-addr localhost:13014 -vv
dfuseeos start -c '' accounthist --common-blocks-store-url=gs://dfuseio-global-blocks-us/eos-mainnet/v3  --accounthist-flush-blocks-interval **20** --accounthist-max-entries-per-account 5 --accounthist-start-block-num 5000000 --accounthist-shard-num 0 --accounthist-stop-block-num **5000200** --common-blockmeta-addr localhost:13014 -vv
dfuseeos start -c '' accounthist --common-blocks-store-url=gs://dfuseio-global-blocks-us/eos-mainnet/v3  --accounthist-flush-blocks-interval **10** --accounthist-max-entries-per-account 5 --accounthist-start-block-num 5000000 --accounthist-shard-num 0 --accounthist-stop-block-num **5000300** --common-blockmeta-addr localhost:13014 -vv

we end up with keys like this:

```
{"data":false,"key":"020000000000ea3055fffffffffffffffe1b"}
{"data":false,"key":"020000000000ea3055fffffffffffffffe1c"}
{"data":false,"key":"020000000000ea3055fffffffffffffffe1d"}
{"data":false,"key":"020000000000ea3055fffffffffffffffe1e"}
{"data":false,"key":"020000000000ea3055fffffffffffffffe1f"}
{"data":false,"key":"020000000000ea3055ffffffffffffffffff"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffcc"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffcd"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffce"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffcf"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffd0"}
{"data":false,"key":"02000090e602ea3055ffffffffffffffffff"}
```

notice how the `fffffffffffffff` key is not deleted..

**Comment by maoueh** [comment]
Note deleted because we use end key `02000090e602ea3055ffffffffffffffffff` as the end key of the range which is exclusive. So if such key exists, it's not deleted (since exclusive end).

This was the same problem at other place, specially when we were querying. Now, we use `actionPrefix(account)` and use the next prefix key so the last `ffffffffffff` key is included. And moreover, the last key will always be `fffffffffffe` now because the ordinal num (new name for history sequence) of the account always start at 1.

**Comment by abourget** [comment]
Was there another ordinal issue?, because I saw this bug even with the ordinal starting at 1, which threw me off..

**Comment by maoueh** [comment]
This very instance was caused because the key was fffffff and the end range was also fffffff.

But yeah, there was another bug causing ordinal to start at 0 instead of 1 like expected. The bug there was caused by wrong assumptions about semantics of kvdb.

When looking for initial ordinal value, we were using Scan. But the calling code was assuming it would return ErrNotFound when no key was found. But it’s to the behaviour of Scan, so the ordinal was starting at 0 instead of the expected 1.
