### ISSUE TITLE
Sometimes the relayer gets stuck 

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#169]
Sometimes the relayer gets stuck 

```
$ check_grpc_health
GRPC HEALTH OK: status: SERVING
```

```
$ curl -s http://localhost:9102 | grep head_block_time_drift
# HELP head_block_time_drift Number of seconds away from real-time
# TYPE head_block_time_drift gauge
head_block_time_drift{app="relayer"} 1946.902627119
```

Nothing getting printed in logs.

Not sure how it is SERVING when it is out of sync?

**Comment by sduchesneau** [comment]
This probably happens because it disconnected from both mindreaders in a way that it could not find a complete chain from its last block to the mindreader block..

ex:
relayer is at block 100
it disconnects from both mindreaders for half a second
it reconnects to mindreader, gets block 102
it reconnects to next mindreader, gets block 103..

the block 101 is missing forever!
the relayer is not able to easily discover that scenario, so the current solution that we use is the      
`--relayer-max-drift duration                             Max delay between live blocks before we die in hope of a better world (default 5m0s)`

when the system is up-to-date (not syncing the chain...), that flag does its job well.
I recommend that you try to enable it.

I will check if we can change the behavior of the healthcheck, but these things are tricky, sometimes you would end up with relayer available just because the mindreaders are lagging behind...
Best would be to implement a proper "hole detection", when we have no active connection =< highest-seen-block-num and we reconnect to a mindreader that is above. That check should be done behind a 'forkDB' so that we also detect if we reconnect below that block num but cannot complete a chain segment to the longest chain...
a bit tricky with lots of edge cases, but I'll look into it.

Until then, see if relayer-max-drift is good enough for you, as it is good enough for us!

**Comment by matthewdarwin** [comment]
ok, I set `relayer-max-drift: 60s` then

It was disabled due to the comment:

`# disabled as it's not working properly`

**Comment by sduchesneau** [comment]
^ probably because of previous state of your implementation (blockmeta ? mindreader not up to date ? only a single mindreader reachable ? etc.)
but keep this issue open, a real fix will need a better detection of a hole (with appropriate logging). readiness should be associated with a "max drift".

**Comment by matthewdarwin** [comment]
We had lots of challenges with configuration before now. Configuration should be setup as recommended now, I hope.

**Comment by sduchesneau** [comment]
@matthewdarwin 
the most likely issue here was that:
1) relayer is connected to mindreader1 and mindreader2
2) mindreader1 restarts and come back online. 
- relayer has not reconnected to mindreader1 yet
- mindreader2 and relayer are now at block 100
3) mindreader2 restarts
4) relayer finally reconnects to mindreader1, now at block 102
5) mindreader2 catches up with upstream blocks
6) relayer finally reconnects to mindreader2 (now at block 110...)

so the relayer never got the block "101" !

Do you think it is possible that this is what happened ? 

Current solutions to this are:
1) having a good delay between any 'restart' on mindreader (waiting for it to have been ready for a while before you restart the next one)
2) having more than 2 mindreaders and only restarting one at a time, so the mindreader3 would have provided the block 101 in the described scenario ^
3) using the max-drift so the relayer detects that it's not advancing and restarts...

solutions 1 and 2 are very specific to how you manage your infrastructure but *shoud* give a good guarantee of no-impact.
solution 3 has the disadvantage of still incurring a small downtime for the configured period, also it may run into restart loop if the chain is not advancing for some reason (or is "running late") in some extreme hardcore scenarios..

I'm currently thinking of a few more solutions, that could be implemented in code:
4) the mindreader could keep a small block buffer and the relayer could request that full block buffer when it connects, so it will most likely fill the gap. (still not perfect, you have to rely on solution "3" in case the buffer is too small, and it increases memory footprint of mindreader and causes some locking on the mindreader when it has to send all the content of its buffer to a consumer.

5) upon reconnecting to a source, the relayer could check the first block that it receives. If it creates a gap, it verifies that it still has other connections that are "alive and well" to close that gap. In case it creates a gap and no other connection is active, restart the 'joining source' (download missing blocks from files...)
The issues with #5 are
a)  that it is not trivial to determine if a given connection is still alive without "arbitrary delays" (1 second, 10 seconds... or we end up with the same delay as max-drift and have not solved anything..)
b) launching blockprocessing from file source can become memory hungry, especially while keeping a buffer of the blocks coming on the live sources. It will end up consuming several GBs of RAM pretty quickly on mainnet...

**Comment by sduchesneau** [comment]
After discussion, we will implement like this:

1) modify the 'max-drift' so it is not based on drift, but actually "block-hole-detection-delay" -> if no "valid (linkable, lastblocknum+1)" new block has been received for that amount of time BUT we did see a block that has blocknum higher than our last processed block (unlinkable), then we trigger the recovery action.

2) modify the "recovery action" -> instead of killing the process, implement this as an "eternal joining source" that retries to join (from blockfiles + live-sources + merger 'premerged blocks'). This will incur a rise in RAM usage when it happens, but it is probably the better scenario anyway.

3) allow requesting a "burst" from the sources (does not apply to connection to the mindreader at the moment, until we do 4)

4) make mindreader keep a few last blocks (ex: 120 last blocks) so it can send them when burst is requested

5) the blockstream request could, instead of asking blindly for a burst, optimistically ask for low_block_num; if unavailable, fallback on requested burst. this change would go in the blockstream server(bstream repo) and in the request (.proto definition)


steps 1 and 2 would be enough to lower significantly the delay to recover from a missed block in upstream services, without risking increased failure rates because of false-positives (we usually set 5 minutes max-drift in prod, 30 seconds without incoming blocks would be well enough to determine that we need to restart joining from block files / premerged blocks ), so time to recovery would go from 5m15s to around 35 seconds 

step 3 would reduce the frequency of incidents for relayer connected to other relayers (filtered relayer mentioned in #173 )

step 4 would apply the improvement of step 3 for relayers connected directly to mindreaders (standard case)

step 5 would decrease the cost of reconnecting to upstream sources and reprocessing large blocks.

**Comment by sduchesneau** [comment]
Variation to 1: remove the max-drift completely. Instead, we periodically (1sec) check that our highest sent block num (linked, in the longest chain) is always on par with the highest "received" block num from our sources. On EOS, if we receive a higher block number, it should become the longest chain "unless we missed some blocks". "Init time" param is also removed. With bullet 2. implemented too, it makes it a lot more snappy to start sending blocks again when disconnected.

**Comment by sduchesneau** [comment]
Fixed in https://github.com/dfuse-io/dfuse-eosio/commit/e0ed30c397db0bdf6f2ae8d235cd73bde1363169

(bullet items "4" and "5" will be moved to new "nice to have" issues)
