### ISSUE TITLE
 database dirty flag set (likely due to unclean shutdown)

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#202]
Since the synchronization node is managed and run by dfuseeos itself, from the test point of view, the stability of the dfuseeos has an impact on synchronization node. How to avoid the abnormal exit caused by this association?

```
./dfuseeos start
Starting dfuse for EOSIO with config file './dfuse.yaml' 
Launching applications: abicodec,apiproxy,blockmeta,booter,dashboard,dgraphql,eosq,eosws,merger,mindreader,relayer,search-archive,search-forkresolver,search-indexer,search-live,search-router,statedb,tokenmeta,trxdb-loader 
Your instance should be ready in a few seconds, here some relevant links:

  Dashboard:        http://localhost:8081

  Explorer & APIs:  http://localhost:8080
  GraphiQL:         http://localhost:8080/graphiql
 
instance stopped, attempting restore from source (operator/operator.go:154) {"source": "snapshot", "command": "nodeos --config-dir=./mindreader --data-dir=/home/surou/Documents/Test_Dfuse/eosio/eos/programs/dfuseeos/dfuse-data/mindreader/data --pause-on-startup"}
<4>warn  2021-01-21T02:43:51.432 nodeos    chain_plugin.cpp:1199         plugin_initialize    ] 13 St13runtime_error: "state" database dirty flag set (log_plugin/to_zap_log_plugin.go:107) 
command terminated with non-zero status (superviser/superviser.go:179) {"status": {"Cmd":"nodeos","PID":4049750,"Exit":2,"Error":{"Stderr":null},"StartTs":1611197031417829539,"StopTs":1611197031434658318,"Runtime":0.016828781,"Stdout":null,"Stderr":null}}
<3>error 2021-01-21T02:43:51.433 nodeos    main.cpp:153                  main                 ] database dirty flag set (likely due to unclean shutdown): replay required (log_plugin/to_zap_log_plugin.go:107) 
cannot find latest snapshot, will replay from blocks.log (superviser/snapshot.go:153) 
restarting node from snapshot, the restart will perform the actual snapshot restoration (operator/operator.go:393) 
Received termination signal, quitting 
Waiting for all apps termination... 
app trxdb-loader triggered clean shutdown 
```

**Comment by maoueh** [comment]
The first recommendation is to run `mindreader` independently from the rest of the stack. This will greatly reduce the chance that an abnormal exit of dfuse-eosio due to other part affects `mindreader` operation, this is true also for `node-manager` app that also manages `nodeos` process.

The next one is to define a good recovery policy through snapshots taken and auto-recovery. Even without dfuse for EOSIO, `nodeos` is at risk of an unclean shutdown for example due to out-of-memory error, server unwanted restart, other causes.

If you don't already have a auto-snapshot taking mechanisms in place, the suggestion in this part is to run `node-manager` app standalone on the side. It will contains another synchronized copy of the chain's data & state, can be used to serve Nodeos RPC API also. This app is responsible for taking automatic snapshots at regular interval.

```
# Storage bucket with path prefix where state snapshots should be done. Ex: gs://example/snapshots
node-manager-snapshot-store-url: <storage location, local path or supported cloud provider bucket>
# Enables restore from the latest snapshot when `nodeos` is unable to start.
node-manager-auto-restore-source: snaphost
#  If non-zero, a snapshot will be taken every {auto-snapshot-modulo} block.
node-manager-auto-snapshot-modulo: 100000 # Decrease for network with heavier traffic to take snapshot more often and shrink time to catch up from latest snapshot to HEAD
# If non-zero, after a successful snapshot, older snapshots will be deleted to only keep that number of recent snapshots
node-manager-number-of-snapshots-to-keep: 5 # Uses 0 to keep them all, useful for eventually regenerating dfuse merged blocks in parallel (not very likely but possible) 
```

When those snapshots exists, you can now configure `mindreader` app to use them also to automatically restore when it's unable to start the `nodeos` process which is almost always solveable with a snapshot restore, mindreader starts in the past and catch up. The required added settings are:

```
# Storage bucket where `node-manager` wrote its snapshot, must be shared with `mindreader` app.
mindreader-snapshot-store-url: <storage location, local path or supported cloud provider bucket>
# Enables restore from the latest snapshot when `nodeos` is unable to start.
mindreader-auto-restore-source: snaphost
```

Everything can run on the same machine as different processes to start. It can also be containerized to run in Kubernetes for example.

Another option is to use the `mindreader-stdin` app. This app is just like `mindreader` app, but doesn't manage `nodeos` process. Instead, it consumes `nodeos` deep mind data through the `stdin` pipe, the invocation looks like `nodes -c <standard nodeos args> | dfuseeos start mindreader-stdin <flag or -c config.yaml file>` (might not be the exact invocation, can link you to docs if you want).

If this answers your question, feel free to close the issue.

**Comment by cppfuns** [comment]
I understand, thank you, I will get familiar with it later
