### ISSUE TITLE
How to use dfuseeos binary directly after running, eosq browser supports custom network?

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#204]
How to use dfuseeos binary([dfuse-eosio_0.1.0-beta8_linux_x86_64.tar.gz](https://github.com/dfuse-io/dfuse-eosio/releases/download/v0.1.0-beta8/dfuse-eosio_0.1.0-beta8_linux_x86_64.tar.gz)) directly after running, eosq browser supports custom network?

I checked the documentation and source code
```
https://github.com/dfuse-io/dfuse-eosio/blob/3ead0373de25616ee2aba768192b3ef76d297939/eosq/README.md#development-on-existing-network

https://github.com/dfuse-io/dfuse-eosio/blob/4721c53b2f0e13efadfad718f2dff67a325b91f6/eosq/src/models/config.ts#L92
```

Try to run the following command before dfuseeos is running
```
export REACT_APP_DFUSE_API_NETWORK="[{id:\"local\",is_test:true,name:\"Local Network\",url:\"http://172.16.18.2:8080\",}]"
./dfuseeos start
```
But other computers are running, the actual access in eosq is still the local address
![image](https://user-images.githubusercontent.com/7980920/105833661-7b516680-6004-11eb-8554-ad9014ddf373.png)

**Comment by maoueh** [comment]
The endpoint eosq uses to connect to the API is defined by the flag `eosq-api-endpoint-url`. The step to expose dfuse for EOSIO to the internet is roughly the following:

- Expose a load balancer that is able to provide access to Nodeos RPC API (proxing to `nodeos` mainly), EOSWS API and GraphQL API (I provide an URL mapping at the end), we provide an `apiproxy` app that does this, it's not a production grade solution but can be used as a starting component, it does not support gRPC connection also
- The exposed balancer must be available to the internet, let take as an example `https://testing.mychain.com`

Now if you configure `eosq-api-endpoint-url: https://testing.mychain.com`, the `eosq` instance will reach `https://testing.mychain.com` for WebSocket and HTTP API call.

Here the "proxy" URL maps (it also contains gRPC method that could be proxied but were not added since the proxy code needs extra support for it): https://github.com/dfuse-io/dfuse-eosio/blob/develop/apiproxy/proxy.go#L57

So to quickly test, if you exposed the `apiproxy-http-listen-addr` value to the internet (`:8080`). It listens to all interface by default, just like much of the other services, so a good practice is to restrict access to all other ports expect this one. Once exposed, changing `eosq-api-endpoint-url` and pointing it to the externally ip/port that is served by `apiproxy` should allow eosq to start showing traffic.

**Comment by maoueh** [comment]
A quick note that Nginx has been used to act as load balancer in front of the various dfuse for EOSIO services. Cloud providers load balancer is also another one if you are using them for hosting the various services.

**Comment by maoueh** [comment]
> export REACT_APP_DFUSE_API_NETWORK="[{id:\"local\",is_test:true,name:\"Local Network\",url:\"http://172.16.18.2:8080\",}]"
./dfuseeos start

`REACT_APP_DFUSE_API_NETWORK` and other `REACT_APP_...` are used only when developing locally eosq, so it has no effect on `dfuseeos` binary.

**Comment by cppfuns** [comment]
Thanks for your answer~

**Comment by cppfuns** [comment]
I need to customize the system token symbol, how to set it?

I see this option in the code
https://github.com/dfuse-io/dfuse-eosio/blob/448bbbb85fcad467e0561f5d926ee9d7acdc5fde/cmd/dfuseeos/cli/common-flag.go#L22
And try to add in dfuse.yaml
`common-chain-core-symbol: "8,RES"`
But after launching, it did not find
`Error: invalid flag common-chain-core-symbol in config file under command start`

**Comment by cppfuns** [comment]
> I need to customize the system token symbol, how to set it?
> 
> I see this option in the code
> https://github.com/dfuse-io/dfuse-eosio/blob/448bbbb85fcad467e0561f5d926ee9d7acdc5fde/cmd/dfuseeos/cli/common-flag.go#L22
> 
> 
> And try to add in dfuse.yaml
> `common-chain-core-symbol: "8,RES"`
> But after launching, it did not find
> `Error: invalid flag common-chain-core-symbol in config file under command start`

I saw it because the latest release version (v0.1.0-beta8) does not support it. I would like to ask, when will the latest version of dfuse-eosio be released? I tried to compile, but there was a problem with eosq-related module compilation. When I try to compile, I will append related errors to this post.

**Comment by maoueh** [comment]
We do not release that often to be honest. And we are currently shipping new feature and we will wait a bit before releasing a new version, probably in weeks.

Being able to compile from source is a must for now. I can try to help here if required. We have support for building ad-hoc Docker image if that can help.

You **must** update `common-chain-id` to fit with your chain, some feature of `TrxDB` requires the Chain ID to be set to work correctly (signature extraction)

**Comment by cppfuns** [comment]
After compiling with the new version, everything is normal and the problem is over

**Comment by cppfuns** [comment]
How to make the dashboard accessible from the Internet? I tried the parameters, but no success. Can this dashboard be accessed from the Internet?

https://github.com/dfuse-io/dfuse-eosio/blob/515bb82773ff05e5f13c74914b0ef71197b795bd/cmd/dfuseeos/cli/dashboard.go#L19

**Comment by cppfuns** [comment]
It is recommended to put this css locally in the project. In China, due to network reasons, this file cannot be loaded
When opening the website, the access is stuck, and eosq will not display until the file request timeout fails.

https://use.fontawesome.com/releases/v5.1.1/css/all.css

**Comment by maoueh** [comment]
Open 2 new issues, one for the dashboard and the other for fontawesome inlining.

**Comment by cppfuns** [comment]
> Open 2 new issues, one for the dashboard and the other for fontawesome inlining.
Well, a new issue has been opened for the CSS issue
https://github.com/dfuse-io/dfuse-eosio/issues/205

This issuse we only discuss dashboard

**Comment by cppfuns** [comment]
This post currently needs to be resolved at the end
When you have time, please answer me. Thank you for replying to my questions during this time. I will organize the problems I encountered into articles later to help other friends in need

How to make the dashboard accessible from the Internet? I tried the parameters, but no success. Can this dashboard be accessed from the Internet?

**Comment by cppfuns** [comment]
Independent question, separate question
