### ISSUE TITLE
why I can’t find the transaction through rest api? How to set this block_count

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#207]
I check the current transaction at block height 149441, 

http://39.106.103.152:8080/tx/be3205fc91cd897433c3ca7c089d95edc9fdfbe56297f745ec34971cb18207eb

why I can’t find the transaction through rest api?

http://39.106.103.152:8080/v0/search/transactions?start_block=0&block_count=149441&limit=10&sort=desc&q=receiver:eosio.token+action:transfer+data.to:xihzz2blorkc

I tried to enlarge the block_count to 200000, but the transaction is still not found

http://39.106.103.152:8080/v0/search/transactions?start_block=0&block_count=200000&limit=10&sort=desc&q=receiver:eosio.token+action:transfer+data.to:xihzz2blorkc

When I delete the block_count, I can check the transaction

http://39.106.103.152:8080/v0/search/transactions?start_block=0&limit=10&sort=desc&q=receiver:eosio.token+action:transfer+data.to:xihzz2blorkc

```
block_count Optional
Number (uint32)     Number of blocks to search from start_block. Depending on sort order, the block_count will count upwards or downwards.
```
How to understand block_count here
block_end = block_start + block_count?

**Comment by maoueh** [comment]
The `/v0/search/transactions` is deprecated, we do not recommend its usage anymore, especially since the API is really hard to understand a the block_start, block_count and sort parameters are inter-related and is a hard to use interface.

The replacement is to use the GraphQL API searchTransactions feature. Here an example on your own endpoint:

http://39.106.103.152:8080/graphiql/?query=cXVlcnkgewogIHNlYXJjaFRyYW5zYWN0aW9uc0ZvcndhcmQocXVlcnk6ICJyZWNlaXZlcjplb3Npby50b2tlbiBhY3Rpb246dHJhbnNmZXIgZGF0YS50bzp4aWh6ejJibG9ya2MiLCBsb3dCbG9ja051bTogMjcxMjgzLCBoaWdoQmxvY2tOdW06IDg3MTI4MykgewogICAgcmVzdWx0cyB7CiAgICAgIHVuZG8KICAgICAgY3Vyc29yCiAgICAgIHRyYWNlIHsKICAgICAgICBibG9jayB7CiAgICAgICAgICBudW0KICAgICAgICAgIGlkCiAgICAgICAgICBjb25maXJtZWQKICAgICAgICAgIHRpbWVzdGFtcAogICAgICAgICAgcHJldmlvdXMKICAgICAgICB9CiAgICAgICAgaWQKICAgICAgICBtYXRjaGluZ0FjdGlvbnMgewogICAgICAgICAgYWNjb3VudAogICAgICAgICAgbmFtZQogICAgICAgICAganNvbgogICAgICAgICAgc2VxCiAgICAgICAgICByZWNlaXZlcgogICAgICAgIH0KICAgICAgfQogICAgfQogIH0KfQo=&variables=e30=

I'm not sure why it doesn't match it, please reproduce using the GraphQL API and I'll take a look if you can reproduce. I'll close for now, re-open if the bug can be reproduced.
