### ISSUE TITLE
add s3 bucket support for storing blocks (one-blocks and hundred-blocks)

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#63]
Allow blocks to be stored in an s3 bucket as an option.  eg minio.

If using a simple s3 server, then consider also this issue
https://github.com/dfuse-io/dfuse-eosio/issues/56

**Comment by maoueh** [comment]
`dstore` our abstraction for file storage/retrieval have support for it: https://github.com/dfuse-io/dstore/blob/develop/s3store.go.

But it seems it's not possible to create the store from a string because the `NewStore` call for `s3` scheme is commented out: https://github.com/dfuse-io/dstore/blob/develop/stores.go#L66

I know we did use it a little, maybe @abourget would know more why it's commented out.

**Comment by matthewdarwin** [comment]
It is possible we could mount s3 storage using s3fs-fuse.

**Comment by abourget** [comment]
We definitely want native S3 storage.  I assumed it was all there and good. I did that recently, probably just forgot to remove the comment.

Do you want to PR that in ?  From what I recall, it's all ready, except this line!

**Comment by fschoell** [comment]
There seems to be an issue with uploading stale files, this is from our logs:
`Jun 17 11:07:09 jungle-dm12b nodeos[51511]: 2020-06-17T11:07:09.794Z (mindreader) failed to upload stale files (mindreader/mindreader.go:238){"error": "moving file \"/var/lib/dfuse/mindreader/work/0020417/0020417661-20200617T000645.0-721b69a1-cf97897e.dat\" to storage: writing \"/var/lib/dfuse/mindreader/work/0020417/0020417661-20200617T000645.0-721b69a1-cf97897e.dat\" to storage \"0020417661-20200617T000645.0-721b69a1-cf97897e.dbin.zst\": uploading to S3 through manager: RequestError: send request failed\ncaused by: Put http://172.22.3.105:9002/jungle-one-blocks/0020417661-20200617T000645.0-721b69a1-cf97897e.dbin.zst: dial tcp 172.22.3.105:9002: connect: cannot assign requested address"}`

Note that this only happens after nodeos is shutting down, while being live the mindreader s3 upload works fine. Maybe the connection is closed to early?

**Comment by maoueh** [comment]
I searched for `cannot assign requested address` on the web and found: https://github.com/golang/go/issues/16012.

It describe a similar issue an explain it's because there is too much resources being used. They give some ideas to augment the resources pool, not sure if it's applicate easily to the s3 sdk client.

When mindreader shut down, maybe it's trying to upload too much blocks in parallel. Will need to think investigate more I guess.

**Comment by sduchesneau** [comment]
Can we close this issue ? There is this issue remaining (https://github.com/dfuse-io/dfuse-eosio/issues/91) but this one here should be closed, no ? the issues with burst uploading of files from mindreader should also have been addressed by all the rework there...

**Comment by matthewdarwin** [comment]
Yes, should be closed.
