### ISSUE TITLE
found a hole in a oneblock files

### ISSUE THREAD

**Issue by Muggle-Du** [dfuse-io/dfuse-eosio#80]
I'm trying to syncing the eos mainnet , and all components were started and all seemed working in a good condition until encountering this error: 
found a hole in a oneblock files (merger/bundle.go:90) {"bundle_lower_block": 1784100, "missing_block_num": 1784169, "missing_block_id": "1f870f97"}
<img width="1043" alt="截屏2020-06-27 下午2 12 05" src="https://user-images.githubusercontent.com/25078682/85916222-17559c80-b881-11ea-8071-004900cef877.png">
By checking the dfuse.log.json , I find blockfiles  /home/adu/eostest/dfuse-data/storage/merged-blocks/0001784100.dbin.zs was not created :
<img width="1111" alt="截屏2020-06-27 下午2 12 33" src="https://user-images.githubusercontent.com/25078682/85916244-66033680-b881-11ea-9273-45709108e174.png">
<img width="1112" alt="截屏2020-06-27 下午2 13 07" src="https://user-images.githubusercontent.com/25078682/85916246-67ccfa00-b881-11ea-8341-8eb4aab05034.png">
<img width="1102" alt="截屏2020-06-27 下午2 13 25" src="https://user-images.githubusercontent.com/25078682/85916248-68659080-b881-11ea-874f-e94e55993b9d.png">
indexer got stuck

**Comment by sduchesneau** [comment]
Hi, from the block ID I see that you are trying to sync EOS Mainnet from the start.
This requires a few customization flags, it does not work out of the box.

I suggest that you first read " Sync'ing a large chain #26 " and try with the "phase1.yaml" approach. The "merge-and-store-directly" flag is key, and also the fact that you need to run mindreader instance separately from the rest to improve your chance of processing 128 million blocks without a hiccup (Most of the dfuse components are not meant to run on a chain that is not "ready" (already synced))
Note that "merge-and-store-directly" does not support "stopping and restarting" the process, so if it stops, you will have to restore your nodeos from a snapshot. 

Your mindreader node is probably broken (dirty state), and you can see this with  "dfuseeos start mindreader -vvv", you will have to restore it from a state snapshot.

Closing this issue, because you are trying to do something that is "guaranteed to *not* work" (as discussed in issue #26)
