### ISSUE TITLE
merger initiates in non-optimal order

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#94]
When merger starts it first figures out what block it is as by looking at storage.  This lookup may take some time (it may take hours if storage is misbehaving).  Meanwhile it is not listening on gprc.

Perhaps gprc socket should be setup first, then connect to storage to figure out where it is at.

```
2020-07-11T18:16:10.146Z (merger) merger initiated (merger/app.go:79)
2020-07-11T18:16:26.832Z (merger) Setting up bundle (merger/merger.go:147){"start": 24661500, "stop": 0, "chunk_size": 100}
2020-07-11T18:16:26.832Z (merger) Creating new bundle (merger/bundle.go:45){"lower_block_num": 24661500, "chunk_size": 100}
2020-07-11T18:16:26.832Z (merger) merger running (merger/app.go:111)
2020-07-11T18:16:26.832Z (merger) starting merger (merger/merger.go:178){"lower_block_num": 24661500}
2020-07-11T18:16:26.832Z (merger) grpc server created (merger/server.go:15)
2020-07-11T18:16:26.832Z (merger) tcp listener created (merger/server.go:22)
2020-07-11T18:16:26.832Z (merger) server registered (merger/server.go:26)
2020-07-11T18:16:26.832Z (merger) listening & serving grpc content (merger/server.go:29){"grpc_listen_addr": ":9000"}
```

**Comment by abourget** [comment]
`merger` / `mindreader` interaction has been a heating debate over here.. we've recently introduced the `Tracker` object, which can help understand where each process stands in a chain.. if it's catch-up mode, or near the live, and that, relative to all sorts of places (the trxdb database, the network through /get_info, the relayer stream, the backing mindreader, an internal hub, a query to blockmeta, etc..)

Ideally, we'd like all those merging issues to be self-resolved by having reactive behaviors.  The merger could start only when he's real-time relative to the head of the chain (as reported by either API nodes, or the highest block reported by all backing `mindreaders`).  Mindreaders, if they discover they are in catch-up, relative to API calls to some other nodes on the network, could start writing the merged blocks themselves.. There's no risks of _capturing_ forks when you're way past the live tip of the chain, so no real chances of losing any data.  Once they get close to head, they could start writing one-block-files instead, and the merger, would start picking them up, because it also knows he's near real-time.  With a good overlap between the two (merger, starting to check for one-block files before the `mindreader` starts writing them), we could effectively have a self-managed system.

What do you think of that?

**Comment by matthewdarwin** [comment]
If you take this one step further mindreader could query what is the last block merger has merged, and if mindreader is in catch up mode and older than where merger is currently, don't bother to even send merged-blocks.  (outping  message in the log saying it is doing so).

This covers the scenario where mindreader is starting from an older snapshot, or was offline for a while.

**Comment by sduchesneau** [comment]
I don't understand the initial issue.

Merger needs to know where to merge.
It finds its starting point usually within less than 20 calls to the storage (looking for 1*, 01*, 001*, 0011*, 0012*, 0013*, 0014*, 00131*, 00132*, 001312*, etc.). if storage is misbehaving so much, it makes sense to me that the merger will not become "ready" (then your monitoring can trigger alert because the merger cannot do its job...)

The merger 'listening' on GRPC does not provide any value, it can only serve the last not-merged blocks and help accelerate the bootstrapping of a new relayer.

It is not the only one of our services that does not listen to GRPC until ready. 

The scenario where mindreader is starting from an older snapshot or was offline for a while is covered in https://github.com/dfuse-io/dfuse-eosio/issues/81 and the coming solution is: that  mindreader that is 'late to the party' will NOT produce one-block-files, only merged block files, and it does not overwrite existing files by default, so it's as if it did not send anything. When it gets close to HEAD, it starts producing one-block-files again.

Do you expect anything else about this issue?

**Comment by matthewdarwin** [comment]
I think the solution of other issues solve the concern here.
